#!/bin/bash
# usually located in ~/.local/share/omarchy/bin
screensaver_in_focus() {
  hyprctl activewindow -j | jq -e '.class == "Screensaver"' >/dev/null 2>&1
}

exit_screensaver() {
  hyprctl keyword cursor:invisible false
  pkill -x tte 2>/dev/null
  pkill -f "alacritty --class Screensaver" 2>/dev/null
  exit 0
}

trap exit_screensaver SIGINT SIGTERM SIGHUP SIGQUIT

hyprctl keyword cursor:invisible true &>/dev/null

EFFECTS=(
  middleout
  matrix
  rain
  decrypt
  randomsequence

  # beams
  # binarypath
  # blackhole
  # bouncyballs
  # bubbles
  # burn
  # colorshift
  # crumble
  # errorcorrect
  # expand
  # fireworks
  # highlight
  # laseretch
  # orbittingvolley
  # overflow
  # pour
  # print
  # rings
  # scattered
  # slice
  # slide
  # spotlights
  # spray
  # swarm
  # sweep
  # synthgrid
  # unstable
  # vhstape
  # waves
  # wipe
)

while true; do
  effect=$(printf "%s\n" "${EFFECTS[@]}" | shuf -n1)

  tte -i ~/.config/omarchy/branding/screensaver.txt \
    --no-color \
    --frame-rate 240 \
    --canvas-width 0 \
    --canvas-height $(($(tput lines) - 2)) \
    --anchor-canvas c \
    --anchor-text c \
    "$effect" &

  while pgrep -x tte >/dev/null; do
    if read -n 1 -t 3 || ! screensaver_in_focus; then
      exit_screensaver
    fi
  done
done
